# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('search', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u67e5\u8be2\u65f6\u95f4')),
            ],
        ),
    ]
