# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GithubModel', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5f53\u524d\u65f6\u95f4')),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u67e5\u8be2\u65f6\u95f4'),
        ),
    ]
